foreground            #BBE9F5
background            #000102
cursor                #92BFCA

# Black
color0  #000202
color8  #69959F

# Red
color1  #3D4D52
color9  #3D4D52

# Green
color2  #55757E
color10 #55757E

# Yellow
color3  #58818B
color11 #58818B

# Blue
color4  #69949F
color12 #69949F

# Magenta
color5  #69949F
color13 #69949F

# Cyan
color6  #94C1CC
color14 #94C1CC

# White
color7  #B1E0EB
color15 #D0E7EC
