[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\x39\x66ile:///home/eric/Downloads/until%20december%20Willix.mp4)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x4\x41\0\0\0+\0\0\t1\0\0\x5\x96\0\0\x4\x41\0\0\0+\0\0\t1\0\0\x5\x96\0\0\0\x1\0\0\0\0\n\0\0\0\x4\x41\0\0\0+\0\0\t1\0\0\x5\x96)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(616 614)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/eric/Downloads/until%20december%20Willix.mp4, file:///home/eric/Downloads/reddit.mp4, file:///home/eric/.local/share/Steam/steamapps/workshop/content/431960/1945149029/105-1055659_dark-winter-forest-wallpaper-1080p-twilight-wn.mp4
times=13900, 0, 0
