source = /home/eric/.config/hypr/wallust-colors.conf

general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = /home/eric/.cache/current_wallpaper.jpg
    color = $background
    blur_passes = 2
}

input-field {
    monitor =
    size = 100, 35
    outline_thickness = 4
    dots_size = 0.30
    dots_spacing = 0.28
    dots_center = true
    outer_color = $color4
    inner_color = $background
    font_color = $foreground
    fade_on_empty = true
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = $foreground
    font_size = 64
    font_family = Noto Sans
    position = 0, 80
    halign = center
    valign = center
}
